#pragma once

//STALLS DEFINES
#define STALL_TYPE_FREE 0
#define STALL_TYPE_RESERVE 1
#define STALL_TYPE_SERVICE 2

#define STALL_STATUS_FREE 0
#define STALL_STATUS_RESERVED 1

//STALLS LOAD ACTIONS
#define LOAD_RESERVED_RESERVE_STALL 1
#define LOAD_RESERVED_FREE_STALL 2
#define LOAD_FREE_FREE_STALL 3

//SCREENS
#define NOT_DELETED_PARKS_SCREEN 1
#define DELETED_PARKS_SCREEN 2
#define STALLS_SCREEN 3
#define DELETED_STALLS_SCREEN 4

//PARKS STATUS
#define PARK_NOT_ACTIVE 0
#define PARK_ACTIVE 1

//PARKS SETTING
#define PARK_SIZE_X 95
#define PARK_SIZE_Y 45
#define STALL_COEFFICIENT 6

//STALLS PRINTING OFFSETS
#define STALLS_PRINT_LEFT_OFFSET 60
#define STALLS_PRINT_BOTTOM_OFFSET 150
#define STALLS_PRINT_TOP_OFFSET 100
#define STALLS_PRINT_RIGHT_OFFSET 490

//STALLS PAGE SHIFT DIRECTION
#define STALLS_SHIFT_DIRECTION_LEFT 1
#define STALLS_SHIFT_DIRECTION_RIGHT 2
#define STALLS_SHIFT_DIRECTION_UP 3
#define STALLS_SHIFT_DIRECTION_DOWN 4
#define STALLS_SHIFT_DIRECTION_HERE 99

//SHOW STALL
#define SHOW_STALLS_CURRENT_TIME 1
#define SHOW_STALLS_CHOSED_TIME 2

//STALL ORIENTATION
#define STALL_HORIZONTAL 1
#define STALL_VERTICAL 2

#define HALF_HOUR_DECIMAL 0.02083333
#define TIME_TO_CHECK_STALLS_NUMBER 5000

//ERROR
#define LOAD_VERSION_ERROR -1
